development:
  adapter: postgresql
  encoding: unicode
  database: Hackthon
  port: 5432
  username: root
  password: exa10sept
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: Hackthon
  port: 5432
  username: root
  password: exa10sept
  host: localhost
